

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: orderidb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  wiremock:
    image: wiremock/wiremock:3.7.0
    ports:
      - "8089:8080"

  order-service:
    build: .
    image: order-service:latest
    depends_on:
      - postgres
      - wiremock
    env_file:
      - .env.docker
    ports:
      - "8083:8083"

volumes:
  pg_data: